### ISSUE TITLE
Quelques fautes d'orthographes

### ISSUE THREAD

**Issue by YaelBusser** [kevinniel/jeux-video#20]
Création/Musique dans la partie Atmosphère
Il y'a des fautes d'orthographe tel qu'un "ou" à la place d'un "où". 
Quelques oublies d'orthographe pour le pluriel pour la lettre "s" comme par exemple"des jeux vidéo"

**Comment by NicolaCVL** [comment]
Voici des liens, le mot "jeux vidéo" est invariables et ne prend pas de "s".
- https://www.lefigaro.fr/langue-francaise/actu-des-mots/2018/11/23/37002-20181123ARTFIG00053-faut-il-ecrire-jeux-video-ou-jeux-videos.php
- https://www.numerama.com/sciences/263296-daccord-robert-on-va-peut-etre-commencer-a-ecrire-jeux-videos.html

Je ne vois pas les "ou" qui devrait être "où".
https://www.lalanguefrancaise.com/orthographe/ou-ou-ou-orthographe/

"ou" prend un accent quand cela parle d'une situations géographique.

**Comment by YaelBusser** [comment]
My bad pour jeux vidéo ^^
Mais pour "où" y'a par exemple la première phrase : La musique de jeu vidéo est la bande son ou tout morceau musical composé pour un jeu vidéo. Le "ou" devrait être "où" pour dire que c'est dans la bande son que tout morceau musical est composé pour un jeu vidéo.
